- name: Generate snake.svg
  uses: Platane/snk@master
  with:
    github_user_name: USERNAME
    outputs: |
      dist/github-contribution-grid-snake.svg
    svg_parameters: |
      --background transparent


on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: fajarRA526
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: "generated snake"
